dbt_project:
  outputs:
    dev:
      account: ckebrjz-ftb46398
      database: analytics
      password: Madurai2023!
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: ranimurugesan
      warehouse: compute_wh
  target: dev
